# General
subscription_name: Azure Subscription
subscription_id: 29523625-6fa5-4d9a-86bc-da000544be7d
resource_group: rg-thadaw-demo-multi-app
location: East Asia
# Azure Key vault
keyvault_name: kv-github-thadaw
keyvault_key: sops-key
service_principle_name: sp_sops_github_action_thadaw